rootProject.name = "otus-java-professional"

include("hw01-gradle")
include("hw02-collections")
include("hw03-testframework")
include("hw04-gc")
include("hw05-aop")
include("hw06-atm")
include("hw07-patterns")
include("hw08-json")
include("hw09-jdbc")
include("hw10-hibernate")
include("hw11-cache")
include("hw12-webserver")
include("hw13-di")
include("hw14-springBoot")
include("hw15-thread")
include("hw16-queues")
include("hw17-gRPC")
include("hw18-webflux:client-service")
include("hw18-webflux:datastore-service")
include("project-web-server")
